[phases.setup]
nixPkgs = [
  "python311",
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "atk-bridge",
  "cups",
  "drm",
  "dbus",
  "at-spi2-atk",
  "xkbcommon",
  "gtk3",
  "pango",
  "cairo",
  "expat",
  "libxkbcommon",
  "libX11",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "mesa"
]

[variables]
PLAYWRIGHT_BROWSERS_PATH="0"

[start]
cmd = "bash -c 'python -m playwright install chromium && python bot.py'"
