[phases.setup]
nixPkgs = ["python311"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install --with-deps chromium"
]

[start]
cmd = "python bot.py"
